# Configuration
LineLength:
  Max: 85

# Exclude certain files
ClassAndModuleChildren:
  Exclude:
    - db/seeds.rb

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

GuardClause:
  Enabled: false