Category.create(name: 'airline')
Category.create(name: 'travel')
Category.create(name: 'business-rewards')
Category.create(name: 'hotel')
Category.create(name: 'cash-back')
Category.create(name: 'other')